version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Rails Test Preparation (Create DB)
          command: bin/rails db:create
      - run:
          name: Rails Test Preparation (Migrate DB)
          command: bin/rails db:migrate
      - run:
          name: Rails Test
          command: bin/rails t
