version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
        environment: 
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD:
      - image: circleci/mysql:8.0.22
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Wait for DB connection
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 180s
      - run:
          name: Rails Test Preparation (Create DB)
          command: bin/rails db:create
      - run:
          name: Rails Test Preparation (Migrate DB)
          command: bin/rails db:migrate
      - run:
          name: Rails Test
          command: bin/rails t
